// --- Nicolas Cuervo --- //

document.querySelector(".Menu-Boton").addEventListener("click", () => {
  document.querySelector(".Nav-Menu").classList.toggle("show");
});

ScrollReveal().reveal('.Header-Contenido-Principal', { delay: 500 });
ScrollReveal().reveal('.Div-Varios-Temas', { delay: 500 });
ScrollReveal().reveal('.Seccion-Politica-Publicidad', { delay: 500 });
ScrollReveal().reveal('.Seccion-Noticia-Dia', { delay: 500 });

// ©Nicolas Rojas 2022 Todos los derechos reservados //